name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: mlugg/setup-zig@v1
    - name: Install deps
      run: sudo apt install git xorriso make
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: ./test.sh
