name: Build and Test X86_64

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: mlugg/setup-zig@v1
    - name: Install deps
      run: sudo apt install qemu-system
    - name: Setup
      run: rustup target add x86_64-unknown-none
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: ./test.sh
    - uses: actions/upload-artifact@v4
      with:
        name: x86_64-iso
        path: navios.iso
        if-no-files-found: error
